name: CI - Terraform & K8s Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Validate Kubernetes YAML with kubeval
        run: |
          docker run --rm -v ${{ github.workspace }}:/work instrumenta/kubeval *.yaml
